export const ROUTES = {
  home: "/",
  shop: "/shop",
  product: (slug: string) => `/products/${slug}`,
  category: (slug: string) => `/categories/${slug}`,
  cart: "/cart",
  checkout: "/checkout",
  login: "/account",
  register: "/account",
  account: "/account",
  profile: "/account/profile",
  shipping: "/account/profile/shipping",
  orders: "/account/orders",
  wishlist: "/wishlist",
} as const;
